### ISSUE TITLE
Alterando a Estrutura do Projeto

### ISSUE THREAD

**Issue by Rayaninha** [desireefernandes/tutoreasy-v2.0#16]
Nós como desenvolvedores decidimos remodelar a estrutura do projeto, para melhor atender as nossas necessidades. As mudanças consistem em trocar a tecnologia utilizada, deixando de usar o _framework_ Laravel e o banco MySQL para aplicar o **NestJS, React e o PostgresSQL**.

**Comment by Gleicianegaldino** [comment]
Estrutura do projeto modificado, passando a utilizar o NestJS.
