### ISSUE TITLE
CRUD Usuário

### ISSUE THREAD

**Issue by Gleicianegaldino** [desireefernandes/tutoreasy-v2.0#3]
Eu como **usuário** quero **o CRUD usuário** para **ter acesso ao sistema e editar ou apagar minhas informações.**

- [x] Creat;
- [x] Read;
- [x] Delete;
- [x] Update.

**Comment by desireefernandes** [comment]
https://github.com/desireefernandes/tutoreasy-v2.0/issues/7#issue-1299333651
