### ISSUE TITLE
CRUD Tutorial

### ISSUE THREAD

**Issue by Gleicianegaldino** [desireefernandes/tutoreasy-v2.0#4]
Eu como **desenvolvedor** quero **desenvolver o CRUD de tutorial** para **o usuário criar tutoriais no sistema.**

- [x] Creat;
- [x] Read;
- [x] Delete;
- [x] Update.

**Comment by desireefernandes** [comment]
CRUD Tutorial -> https://github.com/desireefernandes/tutoreasy-v2.0/issues/7#issue-1299333651
